apiVersion: v1
kind: Service
metadata:
  name: sweeet-code-service
spec:
  selector:
    app: sweeet-code
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Expose the service externally